org: kmpradeep
app: apiproj
service: aws-webscrapper-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  ecr:
    images:
      appimage:
        path: ./
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 'sqs:*'
          Resource: '*'
        - Effect: Allow
          Action: 'logs:*'
          Resource: '*'
	


functions:
  
  email:
    handler: handler.scrapper
    events:
      - httpApi:
          path: /
          method: post
          cors: true # <-- CORS!
  status:
    handler: handler.status
    events:
      - httpApi:
          path: /status/{id}
          method: get
          cors: true # <-- CORS!
  emailaddress:
    handler: handler.draftemail
    events:
      - httpApi:
          path: /draftemail/{id}
          method: get
          cors: true # <-- CORS!
  campground:
    handler: handler.campground
    events:
      - httpApi:
          path: /campground/{name}
          method: get
          cors: true # <-- CORS!
  addemails:
    handler: handler.addemails
    events:
      - httpApi:
          path: /email
          method: post
          cors: true # <-- CORS!

  getemails:
    handler: handler.getemails
    events:
      - httpApi:
          path: /email/{id}
          method: get
  deleteemail:
    handler: handler.deleteemail
    events:
      - httpApi:
          path: /email/{campid}/{email}
          method: get  
  existingEmail:
    handler: handler.existingEmail 
    events:
      - httpApi:
          path: /existemail/{id}
          method: get
  

    

package:
  patterns:
    - '!layerSource.zip'
    - '!.vscode/**'
    - '!.serverless/**'
    - '!.vs/**'
    - '!migrations/**'
    - '!chromedriver'
    - '!chrome'
    - '!lib/**'

plugins:
  - serverless-offline
  - serverless-offline-sqs-external
