org: kmpradeep
app: apiproj
service: aws-webscrapper-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  ecr:
    images:
      appimage:
        path: ./
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 'sqs:*'
          Resource: '*'
        - Effect: Allow
          Action: 'logs:*'
          Resource: '*'
	


functions:
  
  email:
    handler: handler.scrapper
    events:
      - httpApi:
          path: /
          method: post
  status:
    handler: handler.status
    events:
      - httpApi:
          path: /status/{id}
          method: get
  emailaddress:
    handler: handler.draftemail
    events:
      - httpApi:
          path: /draftemail/{id}
          method: get
  webcrawlerjob:
     image:
      name: appimage
     events:
      - sqs: arn:aws:sqs:us-east-2:862836902890:scrapperjobqueue

custom:
  serverless-offline-sqs-external:
    apiVersion: '2012-11-05'
    endpoint: https://sqs.us-east-2.amazonaws.com/862836902890/scrapperjobqueue
    region: us-east-2
    

package:
  patterns:
    - '!layerSource.zip'
    - '!.vscode/**'
    - '!.serverless/**'
    - '!.vs/**'
    - '!migrations/**'
    - '!chromedriver'
    - '!chrome'
    - '!lib/**'

plugins:
  - serverless-offline
  - serverless-offline-sqs-external
