org: kmpradeep
app: sqs-worker
service: webscrapper-sqs-worker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

constructs:
  jobs:
    type: queue
    worker:
      handler: handler.consumer

functions:
  producer:
    handler: handler.producer
    events:
      - httpApi:
          method: post
          path: /produce
    environment:
      QUEUE_URL: ${construct:jobs.queueUrl}

custom:
  serverless-offline-sqs:
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: eu-west-1
    accessKeyId: root
    secretAccessKey: root

plugins:
  - serverless-lift
  - serverless-offline
